# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  vmImage: ubuntu-latest


steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(09ead458-04a3-47fe-94fe-d82d54e0a841)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t acrkubeappdeploy.azurecr.io/mysampleweb-app:tag mysampleweb-app
      az acr login -n acrkubeappdeploy
      docker push acrkubeappdeploy.azurecr.io/mysampleweb-app:tag

- script: cat Manifests/deployment.yml

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kube-contn-app-cont-kube'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'Manifests'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1(09ead458-04a3-47fe-94fe-d82d54e0a841)'
    azureContainerRegistry: 'acrkubeappdeploy.azurecr.io'
    forceUpdate: false