apiVersion : apps/v1
kind: Deployment
metadata:
  name: mysampleapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysampleapp
  template:
    metadata:
      labels:
        app: mysampleapp 
    spec:
      containers:
        - name: mysampleapp 
          image: acrkubeappdeploy.azurecr.io/mysampleapp
          ports:
          - containerPort: 80